{% set name = "idtrackerai" %}
{% set version = "5.2.12" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
{% set python_min = "3.10" %}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/idtrackerai-{{ version }}.tar.gz
  sha256: 1efb7336540979a6e2c7bfb8d3d4e557513da5a0e63106371f62a33ce86b9ec1

build:
  entry_points:
    - idtrackerai_test = idtrackerai.start.__main__:general_test
    - idtrackerai = idtrackerai.start.__main__:main
    - idtrackerai_validate = idtrackerai.validator.__main__:main
    - idtrackerai_video = idtrackerai.video.main:main
    - idtrackerai_csv = idtrackerai.base.postprocess.trajectories_to_csv:main
    - idmatcherai = idtrackerai.idmatcherai.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.2
    - rich >=13.3.1
    - h5py >=3.8.0
    - scipy >=1.10.0
    - opencv >=4.10.0.84
    - pyqt >=5.15.9
    - qtpy >=2.3.1
    - superqt >=0.4.1
    - toml >=0.10.2
    - matplotlib-base >=3.7.0
    - packaging


test:
  imports:
    - idtrackerai
  commands:
    - idtrackerai_test --help
    - idtrackerai --help
    - idtrackerai_validate --help
    - idtrackerai_video --help
    - idtrackerai_csv --help
    - idmatcherai --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://idtracker.ai/latest/
  summary: Idtracker.ai tracks up to 100 unmarked animals from videos recorded in laboratory conditions using artificial intelligence. Free and open source.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
